# Generated by Django 5.0.2 on 2024-02-16 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='slug',
        ),
    ]
